name: Run Python Script

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Run Air Quality Data
        run: python airquality.py

      - name: Run Weather Data
        env:
          WEATHER_DATA_API: ${{ secrets.WEATHER_DATA_API }}
        run: python weatherdata.py
      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f hourly_air_quality.csv
          git add -f hourly_Weather_data.csv

          if git diff --cached --quiet; then
            echo "No changes to CSV files"
          else
            git commit -m "Update hourly air quality and weather data"
            git push
          fi

